[workspace]

members = [
    "hello-world/actix-web",
    "hello-world/astra",
    "hello-world/axum",
    "hello-world/hyper",
    "hello-world/rocket",
    "hello-world/tide",
    "hello-world/warp",
    "hello-world/poem"
]
